### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by flyingluscas** [codecasts/laravel-jwt#19]
Hi @hernandev, me again hehe, I think it would be very good if this project had a contributing guide so that other developers don't make the same mistake I did when I've opened the PR #18, sending to the `master` branch instead of `develop`, what you think?

**Comment by hernandev** [comment]
You can include a PR that adds a `CONTRIBUTING.md` on the root folder, but also, it should go to `develop`.

Only `git flow` can change the master branch directly.

**Comment by hernandev** [comment]
Thanks!

**Comment by flyingluscas** [comment]
Great! I'll prepare a new PR for this tomorrow :)

**Comment by hernandev** [comment]
Thanks

**Comment by flyingluscas** [comment]
@hernandev I think it would be a good idea to make `develop` as the main branch, that way new pull requests go directly to it, what you think?

**Comment by hernandev** [comment]
Included Hacktoberfest label on some issues and PR, so you can all enjoy the perks of the promotion, check more about it here: https://hacktoberfest.digitalocean.com/

**Comment by hernandev** [comment]
Actually that's not even needed anymore, just figured it out.

@flyingluscas making develop default branch has implications on gitflow command line, since it may detect wrongly the production branch as being develop, since it's the default one.

I've just find out I can change the base branch on pull requests so that's not even a problem anymore, I can just change the branch when it comes to the wrong one.

For now, thanks for the contributing guide.
