### ISSUE TITLE
Method issue() does not exist.

### ISSUE THREAD

**Issue by csonti4000** [codecasts/laravel-jwt#33]
I follow the instructions step by step, but throw Exception
`Method issue() does not exist.`
Any Idea what is wrong?

My code:
> function login(Guard $auth){
>         $user2 = User::find(1);
>         $auth->login($user2);
>         $token = $auth->issue();
>         return $token;
>     }

**Comment by hernandev** [comment]
This happens when the Guard is not correctly set.

You must enable the jwt driver on your `config/auth.php`.

Make sure to folow the instructions, if the problem actually persists, you may:

- Provide your code sample leading to the error
- Reopen this issue with more details.

For now, I'm closing this one, feel free to reopen with more details, if that's the case.

Thank you.
